<?php use_script('/modules/minicore-comment/static/comment.js') ?>
<?php $user = $userService->getCurrentUser() ?>

<h5 class="title is-5"><?= text('app', 'comments') ?></h5>

<?php if ($comments): ?>
    <?php foreach ($comments as $comment): ?>
        <article class="media">
            <?= $this->fetch(':comment/avatar', ['size' => 64, 'comment' => $comment]) ?>
            <div class="media-content">
                <?= $this->fetch(':comment/content', ['comment' => $comment, 'user' => $user, 'adminPermission' => $adminPermission]) ?>
                <?php foreach ($comment->getChildren() as $c): ?>
                    <article class="media">
                        <?= $this->fetch(':comment/avatar', ['size' => 48, 'comment' => $c]) ?>
                        <div class="media-content">
                            <?= $this->fetch(':comment/content', ['comment' => $c, 'user' => $user, 'adminPermission' => $adminPermission]) ?>
                        </div>
                    </article>
                <?php endforeach ?>
            </div>
        </article>
    <?php endforeach ?>
<?php else: ?>
    <i style="margin-bottom: 1.5rem; display: block;"><?= text('comment', 'no_comments') ?></i>
<?php endif ?>

<?php if ($moreComments): ?>
    <a class="button is-info is-light is-fullwidth" style="margin-bottom: 1.5rem"><span class="icon" style="padding-right: 2rem"><i class="fas fa-chevron-down"></i></span><?= text('comment', 'load_more_comments') ?></a>
<?php endif ?>
    
<article class="media">
    <figure class="media-left">
        <p class="image is-64x64"><img src="<?= $user->getAvatarUrl() ?>"></p>
    </figure>
    <div class="media-content">
        <div class="field">
            <p class="control">
                <textarea class="textarea" placeholder="<?= text('comment', 'comment') ?>"></textarea>
            </p>
        </div>
        <div class="field">
            <p class="control">
                <button class="button is-primary" data-url="<?= $addUrl ?>"><?= text('comment', 'post_comment') ?></button>
            </p>
        </div>
    </div>
</article>

<?php append_block('scripts') ?>
<script>
</script>
<?php end_block() ?>