<div id="comments">
    <?php if ($comments): ?>
        <?php foreach ($comments as $comment): ?>
            <article class="media" id="comment_<?= $comment->getId() ?>">
                <?= $this->fetch(':comment/avatar', ['size' => 64, 'comment' => $comment]) ?>
                <div class="media-content">
                    <?= $this->fetch(':comment/content', ['comment' => $comment, 'user' => $user, 'hasAdminRight' => $hasAdminRight]) ?>
                    <?php foreach ($comment->getChildren() as $c): ?>
                        <article class="media" id="comment_<?= $c->getId() ?>">
                            <?= $this->fetch(':comment/avatar', ['size' => 48, 'comment' => $c]) ?>
                            <div class="media-content">
                                <?= $this->fetch(':comment/content', ['comment' => $c, 'user' => $user, 'hasAdminRight' => $hasAdminRight]) ?>
                            </div>
                        </article>
                    <?php endforeach ?>
                </div>
            </article>
        <?php endforeach ?>
    <?php else: ?>
        <i id="no_comments_text" style="margin-bottom: 1.5rem; display: block;"><?= text('comment', 'no_comments') ?></i>
    <?php endif ?>
</div>
